name: common_packages
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  intl_translation: ^0.20.0
  flash: ^3.1.1
  flutter_svg: ^2.0.10+1
  restart_app: ^1.2.1
  shared_preferences: ^2.2.3
  in_app_review: ^2.0.9
  url_launcher: ^6.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/icons/
    - assets/images/

