name: common_packages
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0  # Оставляем эту версию для совместимости
  # intl_translation: ^0.20.0
  flash: ^3.1.1
  flutter_svg: ^2.0.17
  restart_app: ^1.3.2
  shared_preferences: ^2.5.1
  in_app_review: ^2.0.10
  url_launcher: ^6.3.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen: ^5.9.0

flutter:
  assets:
    - assets/icons/
    - assets/images/
  
  generate: true